# Generated by Django 4.0.1 on 2022-03-12 04:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='last_report',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 0, 5, 28, 221801, tzinfo=utc), null=True),
        ),
    ]
